name: CI - Auto approve

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created
  
jobs:
  auto-approve:
    uses: bitfunk/action-workflows/.github/workflows/owner-auto-approve.yaml@main
          
