name: CI - Pull Request Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 30 ]

    concurrency:
      group: validation-${{ github.head_ref }}
      cancel-in-progress: true

    env:
      GITHUB_PACKAGE_DOWNLOAD_USER: ${{ github.actor }}
      GITHUB_PACKAGE_DOWNLOAD_KEY: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PACKAGE_UPLOAD_USER: ${{ github.actor }}
      GITHUB_PACKAGE_UPLOAD_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Android SDK
        uses: bitfunk/setup-android@v1.0.0

      - name: Version
        run: ./gradlew --no-daemon --stacktrace versionInfo

      - name: Build
        run: ./gradlew --no-daemon --stacktrace build

      - name: Run Android Device Tests
        uses: bitfunk/android-emulator-runner@v1.0.0
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          avd-name: blueprint-${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew --no-daemon --stacktrace connectedCheck

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace testCodeCoverageReport sonarqube

      - name: Publish Development Version
        run: echo "TODO"
