name: CI - Pull Request Gradle Wrapper Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  pull-request-gradle-wrapper-validation:

    runs-on: ubuntu-latest

    concurrency:
      group: validation-gradle-wrapper-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
