name: CI - Pull Request Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: macos-latest

    concurrency:
      group: validation-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Version
        run: ./gradlew --stacktrace versionInfo

      - name: Build
        run: ./gradlew --stacktrace build

      - name: Run Android instrumented tests
        run: ./gradlew cleanManagedDevices --unused-only &&
          ./gradlew --stacktrace androidGroupDebugAndroidTest
          -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Analyze
        if: ${{ false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew --stacktrace :app-android:createDebugUnitTestCoverageReport sonar

      - name: Publish Development Version
        run: echo "TODO"
