name: CI - Pull-Request Labeler

on:
  - pull_request

jobs:
  add-labels-to-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
