name: CI - Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-release:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Version
        run: ./gradlew --stacktrace versionInfo

      - name: Build
        run: ./gradlew --stacktrace build

      - name: Run Android instrumented tests
        run: ./gradlew cleanManagedDevices --unused-only &&
          ./gradlew --stacktrace androidGroupDebugAndroidTest
          -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish -Prelease

      - name: Publish Release Version
        run: echo "TODO"
